apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-deployment
  labels:
    app: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: amitabhdevops/cicd-app:32cc26cf54ba2db7ddcfaeffb18cd6a5166b01a4
        ports:
        - containerPort: 3000
