apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-app-deployment
  labels:
    app: cicd-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd-app
  template:
    metadata:
      labels:
        app: cicd-app
    spec:
      containers:
      - name: cicd-app
        image: amitabhdevops/cicd-app:f538a3b4c48bf8bff629db84c64b4df0960cdae9
        ports:
        - containerPort: 3000
